apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app1
  template:
    metadata:
      labels:
        app: python-app1
    spec:
      containers:
      - name: python-app1
        image: saadudeenregistry247.azurecr.io/python-app1:latest
        ports:
        - containerPort: 8000


---
apiVersion: v1
kind: Service
metadata:
  name: python-app-service1
spec:
  selector:
    app: python-app1
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8000
  type: LoadBalancer